
name: Go

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_CONTAINER: ${{ secrets.POSTGRES_CONTAINER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
      id: go

    - name: installing golang migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
        ls -l
        sudo mv migrate /usr/bin/migrate
        which migrate
    - name: Get PostgreSQL IP
      id: get-postgres-ip
      run: |
       sleep 2
       IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres)
       echo "POSTGRES_IP=$IP" >> $GITHUB_ENV
    - name: Run migrations
      run: make migrateup     
      env:
       POSTGRES_HOST: ${{ env.POSTGRES_IP }}
    - name: Test
      run: make test  
