name: Go

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
      id: go
    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate
    - name: Set DNS
      run: echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
    - name: Debug POSTGRES_HOST
      run: echo "POSTGRES_HOST is $POSTGRES_HOST"
    - name: Test Postgres Connection
      run: psql -h postgres -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "SELECT 1"
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    - name: Run migrations
      run: make migrateup
      env:
        POSTGRES_HOST: postgres
    - name: Test
      run: make test